Repository 19-Takify/19-taskify, pull requests merged in 2024-04, with the labels that each got.

#3 [fix] template 수정
  .github/ISSUE_TEMPLATE/feat.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/ISSUE_TEMPLATE/style.md
  .github/ISSUE_TEMPLATE/✨feat.md
  .github/ISSUE_TEMPLATE/🎨style.md
  .github/ISSUE_TEMPLATE/🐞fix.md
  .github/ISSUE_TEMPLATE/🔨refactor.md
  .github/pull_request_template.md
  src/components/Button/ButtonAddCard/ButtonAddCard.module.scss
  src/components/Button/ButtonAddCard/index.tsx
  src/components/Button/ButtonAddColumn/ButtonAddColumn.module.scss
  src/components/Button/ButtonAddColumn/index.tsx
  src/components/Button/ButtonConfirm/ButtonConfirm.module.scss
  src/components/Button/ButtonConfirm/index.tsx
  src/components/Button/ButtonDashboard/ButtonDashboard.module.scss
  src/components/Button/ButtonDashboard/index.tsx
  src/components/Button/ButtonDelete/ButtonDelete.module.scss
  src/components/Button/ButtonDelete/index.tsx
  src/components/Button/ButtonSign/ButtonSign.module.scss
  src/components/Button/ButtonSign/index.tsx
Labels: fix

#13 [feat] 토스트 만들기
  package-lock.json
  package.json
  src/apis/init.ts
  src/constants/index.ts
  src/constants/toastText.ts
  src/pages/_app.page.tsx
  src/pages/index.page.tsx
  src/styles/reset.scss
  src/utils/init.ts
  src/utils/setToast.ts
Labels: feat

#4 [refactor] 버튼 컴포넌트 구조 변경
  public/svgs/add.svg
  public/svgs/arrow.svg
  public/svgs/calendar.svg
  public/svgs/crown.svg
  public/svgs/taskify-logo.svg
  src/components/Button/ButtonAddCard/ButtonAddCard.module.scss
  src/components/Button/ButtonAddCard/index.tsx
  src/components/Button/ButtonAddColumn/ButtonAddColumn.module.scss
  src/components/Button/ButtonAddColumn/index.tsx
  src/components/Button/ButtonConfirm/ButtonConfirm.module.scss
  src/components/Button/ButtonConfirm/index.tsx
  src/components/Button/ButtonDashboard/ButtonDashboard.module.scss
  src/components/Button/ButtonDashboard/index.tsx
  src/components/Button/ButtonDelete/ButtonDelete.module.scss
  src/components/Button/ButtonDelete/index.tsx
  src/components/Button/ButtonSign/ButtonSign.module.scss
  src/components/Button/ButtonSign/index.tsx
  src/components/Button/ModalButton/ModalButton.module.scss
  src/components/Button/ModalButton/index.tsx
  src/components/Button/PageButton/PageButton.module.scss
  src/components/Button/PageButton/index.tsx
  src/styles/reset.scss
Labels: refactor

#14 [feat] sidemenu component
  public/svgs/add-box.svg
  public/svgs/taskify-logo.svg
  src/components/Button/Button.module.scss
  src/components/Button/index.tsx
  src/components/SideMenu/SideMenu.module.scss
  src/components/SideMenu/index.tsx
Labels: feat

#20 [feat] 📜드롭다운 만들기
  public/svgs/arrow-down.svg
  public/svgs/arrow-top.svg
  public/svgs/check.svg
  public/svgs/taskify-logo.svg
  src/components/Button/Button.module.scss
  src/components/Button/index.tsx
  src/components/Dropdown/DropDownItem/DropDownItem.module.scss
  src/components/Dropdown/DropDownItem/index.tsx
  src/components/Dropdown/Dropdown.module.scss
  src/components/Dropdown/index.tsx
Labels: feat

#29 [fix]프로필 이미지 리스트 버그 수정 및 버튼 컴포넌트 버그 수정
  src/components/Button/ModalButton/ModalButton.module.scss
  src/components/Button/ModalButton/index.tsx
  src/components/Button/PageButton/PageButton.module.scss
  src/components/Button/PageButton/index.tsx
  src/components/Card/Card.module.scss
  src/components/Card/index.tsx
  src/components/Profile/ProfileIcon/ProfileIcon.module.scss
  src/components/Profile/ProfileIcon/index.tsx
  src/components/Profile/ProfileIconList/ProfileIconList.module.scss
  src/components/Profile/ProfileIconList/index.tsx
  src/hooks/init.ts
  src/hooks/useIsDesiredSize.ts
Labels: fix

#11 [feat] card 컴포넌트
  src/components/Button/PageButton/PageButton.module.scss
  src/components/Card/Card.module.scss
  src/components/Card/index.tsx
Labels: feat

#27 [feat] 메인 페이지 만들기
  public/favicon.ico
  public/images/main-section.webp
  public/svgs/create-todo.svg
  public/svgs/dashboard-invite.svg
  public/svgs/dashboard-member.svg
  public/svgs/dashboard-setting.svg
  public/svgs/dashboard.svg
  public/svgs/email.svg
  public/svgs/facebook.svg
  public/svgs/header-logo.svg
  public/svgs/header-small-logo.svg
  public/svgs/instagram.svg
  public/svgs/taskify-logo.svg
  src/components/Button/ModalButton/ModalButton.module.scss
  src/components/Button/ModalButton/index.tsx
  src/components/Button/PageButton/PageButton.module.scss
  src/constants/pageUrl.ts
  src/hooks/useIsDesiredSize.ts
  src/pages/_app.page.tsx
  src/pages/index.module.scss
  src/pages/index.page.tsx
  src/styles/reset.scss
Labels: feat

#30 [feat] 회원가입 페이지
  public/svgs/taskify-vertical-logo.svg
  src/components/Button/PageButton/PageButton.module.scss
  src/components/Inputs/Input/Input.module.scss
  src/constants/errorMessage.ts
  src/pages/signup/Signup.module.scss
  src/pages/signup/components/SignupForm/SignupForm.module.scss
  src/pages/signup/components/SignupForm/index.tsx
  src/pages/signup/index.page.tsx
  src/styles/reset.scss
  src/utils/cookie.ts
Labels: feat

#23 [Feat] header 컴포넌트
  public/svgs/Taskify.svg
  public/svgs/invite.svg
  public/svgs/logo.svg
  public/svgs/menu.svg
  public/svgs/setting.svg
  src/components/Header/DashBoard/DashBoard.module.scss
  src/components/Header/DashBoard/index.tsx
  src/components/Header/LandingPage/LoginHeader.module.scss
  src/components/Header/LandingPage/index.tsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/Modal.tsx
  src/components/Modal/Potal.tsx
  src/hooks/useModalClose.js
  src/pages/_document.page.tsx
Labels: feat

#7 [feat] getLayout 구현
  src/components/Button/ModalButton/ModalButton.module.scss
  src/components/Button/ModalButton/index.tsx
  src/components/Button/PageButton/PageButton.module.scss
  src/components/Header/DashBoard/DashBoardHeader.module.scss
  src/components/Header/DashBoard/index.tsx
  src/components/Header/LandingPage/LandingHeader.module.scss
  src/components/Header/LandingPage/index.tsx
  src/components/Layout/DashBoardLayout/DashBoardLayout.module.scss
  src/components/Layout/DashBoardLayout/index.tsx
  src/components/SideMenu/index.tsx
  src/pages/_app.page.tsx
  src/pages/dashboard/index.page.tsx
Labels: feat

#38 [feat] ⚙️ 대시보드 관리 페이지 만들기
  .gitignore
  next.config.mjs
  public/svgs/arrow-left.svg
  public/svgs/arrow-right.svg
  public/svgs/check-white.svg
  public/svgs/check.svg
  public/svgs/default-profile.svg
  public/svgs/plus.svg
  src/apis/axios.ts
  src/components/Button/PageButton/PageButton.module.scss
  src/components/Inputs/DatePicker/DatePicker.module.scss
  src/hooks/useObserver.ts
  src/pages/dashboard/edit/components/DashboardEdit/Dashboard.module.scss
  src/pages/dashboard/edit/components/DashboardEdit/index.tsx
  src/pages/dashboard/edit/components/DashboardManager/DashboardManager.module.scss
  src/pages/dashboard/edit/components/DashboardManager/index.tsx
  src/pages/dashboard/edit/index.page.tsx
  src/pages/dashboard/edit/style/edit.page.module.scss
Labels: feat

#47 [feat] 404 페이지 만들기
  src/components/Error/Error.module.scss
  src/components/Loading/Loading.module.scss
  src/pages/404.module.scss
  src/pages/404.page.tsx
Labels: feat

#32 [feat] 로그인 페이지
  src/apis/axios.ts
  src/pages/login/Login.module.scss
  src/pages/login/components/LoginForm/LoginForm.module.scss
  src/pages/login/components/LoginForm/index.tsx
  src/pages/login/components/index.ts
  src/pages/login/index.page.tsx
  src/pages/login/types/index.ts
  src/pages/signup/components/SignupForm/index.tsx
  src/pages/signup/index.page.tsx
Labels: feat

#45 [feat] api 인증 및 get,post,put,delete 구현
  src/apis/axios.ts
  src/apis/httpClient.ts
  src/components/Button/PageButton/PageButton.module.scss
  src/utils/constants.ts
  src/utils/cookie.ts
Labels: feat

#49 [refactor] 대시보드 헤더, 사이드바 수정(스타일, 기능)
  next.config.mjs
  public/svgs/file-add.svg
  public/svgs/header-small-logo-purple.svg
  public/svgs/menu.svg
  robots.txt
  src/components/Button/BackButton/BackButton.module.scss
  src/components/Button/BackButton/index.tsx
  src/components/Button/PageButton/PageButton.module.scss
  src/components/Header/DashBoard/DashBoardHeader.module.scss
  src/components/Header/DashBoard/index.tsx
  src/components/Layout/DashBoardLayout/index.tsx
  src/components/Meta/index.tsx
  src/components/SideMenu/SideMenu.module.scss
  src/components/SideMenu/index.tsx
  src/constants/toastText.ts
  src/hooks/useCurrentUrl.ts
  src/hooks/useIsDesiredSize.ts
  src/pages/404.module.scss
  src/pages/404.page.tsx
  src/pages/_app.page.tsx
  src/pages/dashboard/[id]/edit/components/DashboardEdit/Dashboard.module.scss
  src/pages/dashboard/[id]/edit/components/DashboardEdit/index.tsx
  src/pages/dashboard/[id]/edit/components/DashboardManager/DashboardManager.module.scss
  src/pages/dashboard/[id]/edit/components/DashboardManager/index.tsx
  src/pages/dashboard/[id]/edit/index.page.tsx
  src/pages/dashboard/[id]/edit/style/edit.page.module.scss
  src/pages/dashboard/[id]/index.page.tsx
  src/pages/dashboard/edit/index.page.tsx
  src/pages/index.page.tsx
  src/pages/login/index.page.tsx
  src/pages/mypage/components/PasswordChnage/Password.module.scss
  src/pages/mypage/components/PasswordChnage/index.tsx
  src/pages/mypage/components/Profile/Profile.module.scss
  src/pages/mypage/components/Profile/index.tsx
  src/pages/mypage/index.page.tsx
  src/pages/mypage/style/mypage.module.scss
  src/pages/signup/index.page.tsx
  src/styles/colors.scss
Labels: refactor

#62 [fix] 로그인, 회원가입 페이지 모바일 레이아웃 깨짐 현상
  src/components/Inputs/DatePicker/DatePicker.module.scss
  src/components/Inputs/Input/Input.module.scss
  src/pages/login/Login.module.scss
  src/pages/signup/Signup.module.scss
Labels: fix, style

#60 fix: max-width 이슈 수정
  public/robots.txt
  src/components/Meta/index.tsx
  src/pages/index.module.scss
  src/pages/index.page.tsx
Labels: fix

#56 [feat] modal 수정
  src/components/Modal/Modal.module.scss
  src/components/Modal/Modal.tsx
  src/components/Modal/Modal/Modal.module.scss
  src/components/Modal/Modal/index.tsx
  src/components/Modal/ModalPopOver/ModalDropdown.module.scss
  src/components/Modal/ModalPopOver/index.tsx
  src/components/Modal/ToDoModal/ToDOModal.module.scss
  src/components/Modal/ToDoModal/index.tsx
  src/hooks/useModalClose.js
  src/hooks/useModalClose.ts
Labels: feat

#58 [feat] 인증/인가
  src/apis/axios.ts
  src/constants/auth.ts
  src/constants/errorMessage.ts
  src/hooks/useAuth.ts
  src/hooks/useUser.ts
  src/hooks/useUserForPage.ts
  src/middleware.page.ts
  src/pages/_app.page.tsx
  src/pages/bongsong/components/Box/index.tsx
  src/pages/bongsong/components/Card/index.tsx
  src/pages/bongsong/index.page.tsx
  src/pages/login/components/LoginForm/index.tsx
  src/pages/signup/components/SignupForm/index.tsx
  src/store/auth.ts
  src/types/auth.ts
  src/types/index.ts
  src/utils/auth.ts
  src/utils/cookie.ts
  src/utils/isDocument.ts
Labels: feat

#69 [feat] Header, ~Page 컴포넌트 유저 전역 상태 적용 + 로그아웃
  src/components/Header/DashBoard/DashBoardHeader.module.scss
  src/components/Header/DashBoard/index.tsx
  src/pages/dashboard/[id]/edit/index.page.tsx
  src/pages/dashboard/[id]/index.page.tsx
  src/pages/mypage/index.page.tsx
  src/styles/reset.scss
Labels: feat

#75 [fix] vercel.json rewrites 삭제
  vercel.json
Labels: fix

#71 [feat] 작업한 부분 API 연결
  src/components/Button/BackButton/BackButton.module.scss
  src/components/Dropdown/DropDownItem/index.tsx
  src/components/Header/DashBoard/index.tsx
  src/components/Layout/DashBoardLayout/index.tsx
  src/components/SideMenu/SideMenu.module.scss
  src/components/SideMenu/index.tsx
  src/pages/dashboard/[id]/edit/components/DashboardEdit/Dashboard.module.scss
  src/pages/dashboard/[id]/edit/components/DashboardEdit/index.tsx
  src/pages/dashboard/[id]/edit/components/DashboardManager/DashboardManager.module.scss
  src/pages/dashboard/[id]/edit/components/DashboardManager/index.tsx
  src/pages/dashboard/[id]/edit/index.page.tsx
  src/pages/dashboard/[id]/edit/style/edit.page.module.scss
  src/pages/dashboard/[id]/edit/type/editType.ts
  src/pages/dashboard/[id]/index.page.tsx
  src/pages/index.page.tsx
  src/pages/login/Login.module.scss
  src/pages/mypage/components/PasswordChange/Password.module.scss
  src/pages/mypage/components/PasswordChange/index.tsx
  src/pages/mypage/components/Profile/index.tsx
  src/pages/mypage/index.page.tsx
  src/pages/mypage/style/mypage.module.scss
  src/store/dashboard.ts
  src/styles/fonts.scss
  src/styles/reset.scss
Labels: feat

#79 [fix] 초대 불러오기 api 권한 이슈 수정
  src/components/SideMenu/index.tsx
  src/pages/dashboard/[id]/edit/index.page.tsx
Labels: fix

#76 [feat]대시보드 페이지
  package-lock.json
  package.json
  public/svgs/close.svg
  public/svgs/kebab.svg
  public/svgs/unsubscribe.svg
  src/components/Button/PageButton/PageButton.module.scss
  src/components/Card/Card.module.scss
  src/components/Card/index.tsx
  src/components/Circle/Circle.module.scss
  src/components/Circle/index.tsx
  src/components/Layout/DashBoardLayout/index.tsx
  src/components/Modal/Comment/Comment.tsx
  src/components/Modal/Comment/CommentList.tsx
  src/components/Modal/ModalPopOver/index.tsx
  src/components/Modal/ToDoModal/index.tsx
  src/components/SideMenu/SideMenu.module.scss
  src/components/SideMenu/index.tsx
  src/hooks/useDateFormat.ts
  src/pages/dashboard/[id]/components/Column/Column.module.scss
  src/pages/dashboard/[id]/components/Column/index.tsx
  src/pages/dashboard/[id]/index.page.tsx
  src/pages/mydashboard/components/InvitedDashboard/InvitedDashboard.module.scss
  src/pages/mydashboard/components/InvitedDashboard/index.tsx
  src/pages/mydashboard/components/SearchDashboard/SearchDashboard.module.scss
  src/pages/mydashboard/components/SearchDashboard/index.tsx
  src/pages/mydashboard/index.page.tsx
  src/pages/mydashboard/myDashboard.module.scss
  src/store/dashboard.ts
Labels: feat

#81 [refactor] user 사용성 개선
  src/hooks/useUserForPage.ts
  src/middleware.page.ts
  src/pages/_app.page.tsx
  src/pages/bongsong/index.page.tsx
  src/pages/dashboard/[id]/edit/index.page.tsx
  src/pages/mypage/index.page.tsx
  src/store/auth.ts
  src/utils/auth.ts
  src/utils/cookie.ts
Labels: refactor

#83 Feat/basic modal
  src/apis/httpClient.ts
  src/components/Modal/InviteDashboardModal/InviteDashboard.module.scss
  src/components/Modal/InviteDashboardModal/index.tsx
  src/components/Modal/ManageColumnModal/ManageColumnModal.module.scss
  src/components/Modal/ManageColumnModal/index.tsx
  src/components/Modal/Modal/Modal.module.scss
  src/components/Modal/NewColumnModal/NewColumnModal.module.scss
  src/components/Modal/NewColumnModal/index.tsx
  src/components/Modal/NewDashboardModal/NewDashboardModal.module.scss
  src/components/Modal/NewDashboardModal/index.tsx
  src/constants/colors.ts
  src/constants/errorMessage.ts
  src/pages/bongsong/index.page.tsx
Labels: feat

#84 [feat] 캐러셀 추가
  public/svgs/next-button.svg
  public/svgs/prev-button.svg
  src/components/Button/PageButton/PageButton.module.scss
  src/components/Card/index.tsx
  src/components/Header/DashBoard/DashBoardHeader.module.scss
  src/components/Header/DashBoard/index.tsx
  src/components/Modal/Modal/Modal.module.scss
  src/components/Profile/ProfileIcon/index.tsx
  src/components/SideMenu/index.tsx
  src/components/Tag/index.tsx
  src/pages/dashboard/[id]/components/Column/Column.module.scss
  src/pages/dashboard/[id]/components/Column/index.tsx
  src/pages/dashboard/[id]/index.page.tsx
  src/pages/mydashboard/index.page.tsx
Labels: feat

#88 [fix]: 버그 수정 및 로딩 상태 추가
  src/components/Header/DashBoard/DashBoardHeader.module.scss
  src/components/Loading/Loading.module.scss
  src/components/Loading/index.tsx
  src/hooks/useRouterLoading.ts
  src/pages/404.page.tsx
  src/pages/dashboard/[id]/components/Column/Column.module.scss
  src/pages/dashboard/[id]/components/Column/index.tsx
  src/pages/dashboard/[id]/edit/index.page.tsx
  src/pages/dashboard/[id]/index.page.tsx
  src/pages/index.page.tsx
  src/pages/mydashboard/components/InvitedDashboard/InvitedDashboard.module.scss
  src/pages/mydashboard/components/InvitedDashboard/index.tsx
  src/pages/mydashboard/index.page.tsx
  src/pages/mypage/index.page.tsx
Labels: fix

#89 [fix] 스타일 수정
  src/components/Button/BackButton/BackButton.module.scss
  src/hooks/useRouterLoading.ts
  src/pages/_app.page.tsx
  src/pages/dashboard/[id]/edit/components/DashboardEdit/Dashboard.module.scss
  src/pages/dashboard/[id]/edit/components/DashboardManager/index.tsx
  src/pages/dashboard/[id]/edit/style/edit.page.module.scss
  src/pages/mydashboard/myDashboard.module.scss
Labels: fix

#93 [fix] 스타일 수정
  src/components/Button/BackButton/BackButton.module.scss
  src/components/Button/PageButton/PageButton.module.scss
  src/pages/dashboard/[id]/edit/style/edit.page.module.scss
  src/pages/mypage/style/mypage.module.scss
Labels: fix, style

#90 [refactor] 사이드 메뉴, 대시보드 모달 적용
  src/components/Header/DashBoard/index.tsx
  src/components/Modal/DeleteModal/index.tsx
  src/components/Modal/ManageColumnModal/index.tsx
  src/components/Modal/NewColumnModal/index.tsx
  src/components/Modal/NewDashboardModal/NewDashboardModal.module.scss
  src/components/Modal/ToDoModal/index.tsx
  src/components/SideMenu/index.tsx
  src/constants/colors.ts
  src/pages/bongsong/components/Box/index.tsx
  src/pages/bongsong/components/Card/index.tsx
  src/pages/bongsong/index.page.tsx
  src/pages/dashboard/[id]/components/Column/index.tsx
  src/pages/mydashboard/components/InvitedDashboard/index.tsx
  src/pages/mydashboard/components/SearchDashboard/index.tsx
  src/pages/mydashboard/index.page.tsx
Labels: refactor

#95 [fix] 댓글 수정 시 원래 값이 안 들어감
  src/components/Modal/Comment/Comment.tsx
Labels: fix

#97 [fix] 로그인 페이지 로딩 상태
  src/pages/login/index.page.tsx
Labels: feat, fix

#106 Feat/confirm modal
  src/components/Modal/DeleteModal/index.tsx
  src/components/Modal/InviteDashboardModal/index.tsx
  src/components/Modal/ManageColumnModal/index.tsx
  src/components/SideMenu/index.tsx
  src/pages/dashboard/[id]/edit/components/DashboardManager/index.tsx
  src/pages/dashboard/[id]/edit/index.page.tsx
  src/pages/dashboard/[id]/index.page.tsx
Labels: feat

#107 [fix] 사이드 메뉴 계속 열려있는 이슈 수정
  src/components/SideMenu/index.tsx
Labels: fix

#99 [fix] 중복 초대 발송
  src/components/Modal/InviteDashboardModal/index.tsx
Labels: fix

#73 [style] 회원가입, 로그인 페이지 CSS 레이아웃 깨짐 현상 해결
  src/pages/login/Login.module.scss
  src/pages/login/index.page.tsx
  src/pages/signup/Signup.module.scss
  src/pages/signup/index.page.tsx
Labels: style

#105 [style] ModalButton disabled 스타일링
  src/components/Button/ModalButton/ModalButton.module.scss
  src/components/Modal/NewDashboardModal/NewDashboardModal.module.scss
Labels: style

#101 [fix] 초대 기능 수정
  src/pages/mydashboard/components/InvitedDashboard/index.tsx
  src/pages/mydashboard/components/SearchDashboard/SearchDashboard.module.scss
  src/pages/mydashboard/components/SearchDashboard/index.tsx
  src/pages/mydashboard/index.page.tsx
  src/pages/mydashboard/myDashboard.module.scss
Labels: fix

#110 [fix] 스타일 수정
  src/pages/index.module.scss
Labels: fix, style

#111 [fix] 접근 권한 없이 대시보드 페이지 접속 시 에러
  src/constants/pageUrl.ts
  src/middleware.page.ts
  src/utils/auth.ts
Labels: fix

#113 [fix] 텍스트 길이 및 모달 수정
  src/components/Card/Card.module.scss
  src/components/Card/index.tsx
  src/components/Modal/Comment/Comment.module.scss
  src/components/Modal/ManageColumnModal/index.tsx
  src/components/Modal/Modal/Modal.module.scss
  src/components/Modal/ModalPopOver/index.tsx
  src/components/Modal/ToDoModal/ToDOModal.module.scss
  src/components/Modal/ToDoModal/index.tsx
  src/components/SideMenu/SideMenu.module.scss
  src/components/Tag/Tag.module.scss
  src/pages/dashboard/[id]/components/Column/Column.module.scss
  src/pages/dashboard/[id]/components/Column/index.tsx
  src/pages/mydashboard/components/InvitedDashboard/InvitedDashboard.module.scss
  src/styles/globals.scss
  src/styles/text.scss
Labels: fix, style

#116 [style] 삭제 모달 스타일 작업
  src/components/Modal/DeleteModal/DeleteColumnModal.module.scss
  src/components/Modal/ManageColumnModal/ManageColumnModal.module.scss
Labels: style

#121 [fix] 초대 받은 목록 검색 수정
  src/components/Card/Card.module.scss
  src/components/Card/index.tsx
  src/components/Modal/ToDoModal/index.tsx
  src/pages/mydashboard/components/SearchDashboard/index.tsx
Labels: fix

#119 [feat] editToDo 모달
  public/svgs/close-white.svg
  public/svgs/pen.svg
  src/components/Button/ModalButton/index.tsx
  src/components/ColorPicker/ColorPicker.module.scss
  src/components/ColorPicker/index.tsx
  src/components/Dropdown/index.tsx
  src/components/Inputs/Input/Input.module.scss
  src/components/Inputs/Input/index.tsx
  src/components/Modal/EditToDoModal/EditToDoModal.module.scss
  src/components/Modal/EditToDoModal/index.tsx
  src/components/Modal/Modal/index.tsx
  src/components/Modal/ModalPopOver/index.tsx
  src/components/Modal/ToDoModal/index.tsx
  src/components/Profile/ProfileIconList/index.tsx
  src/components/SideMenu/index.tsx
  src/constants/color.ts
  src/hooks/useFilePreview.ts
  src/pages/dashboard/[id]/components/Column/index.tsx
  src/pages/dashboard/[id]/edit/components/DashboardEdit/index.tsx
  src/pages/dashboard/[id]/index.page.tsx
  src/utils/dateCalculator.ts
  src/utils/stringUtils.ts
Labels: feat

#124 [fix] editTioDo modal 버그 수정
  src/components/Modal/EditToDoModal/index.tsx
  src/pages/dashboard/[id]/components/Column/index.tsx
Labels: fix

#126 [fix]todo 모달 수정
  public/images/og-kakao.png
  public/images/og-twitter.png
  src/components/Card/index.tsx
  src/components/Meta/index.tsx
  src/components/Modal/EditToDoModal/index.tsx
  src/components/Modal/ToDoModal/index.tsx
  src/constants/color.ts
  src/constants/division.ts
Labels: fix

#128 [style] 헤더 프로필 팝오버 글자색
  src/components/Header/DashBoard/DashBoardHeader.module.scss
Labels: style

#130 [fix] 대시보드 페이지 카드 이미지 lazy loading 추가
  src/components/Card/index.tsx
  src/pages/login/Login.module.scss
  src/pages/signup/Signup.module.scss
Labels: fix, style

#131 [fix] 스타일 수정
  src/pages/index.module.scss
Labels: fix, style
